version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # TODO: add your code here (delete this line and follow the indent conventions)
  
  app:
    # TODO: you will need to add to this
    build: ./backend
    environment:
      - REDIS_HOST=redis
    ports:
      - "5555:5000"
    depends_on:
      - redis # this depends on the redis container (which we called redis at the top of this file)
  frontend:
    build: ./frontend
    ports:
      - "3901:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://app:5555 # this defines the URL the frontend makes requests to
    depends_on:
      - app # this depends on the backend container (which we called web at the top of this file)
